### ISSUE TITLE
Replacing translation resource with new one raises error on next email trigger

### ISSUE THREAD

**Issue by nobodykid** [killbill/killbill-email-notifications-plugin#50]
Hello, I'm currently using the v0.7.2 plugin on my Killbill system and I seem to encounter a weird bug

Whenever I update existing email templates through another call to the API, it works fine and it will update on next trigger. But when it comes to the translation resource, I always get error from my template not able to found the reference within the translation resource
```
2022-10-26T13:05:36,007+0000 lvl='WARN', log='EmailNotificationListener', th='bus_ext_events-th', xff='', rId='', tok='92a48023-98c4-4641-95b0-73424b62529e', aRId='1', tRId='1', No method or field with name 'text.invoiceTitle' on line 5
com.samskivert.mustache.MustacheException$Context: No method or field with name 'text.invoiceTitle' on line 5
        at com.samskivert.mustache.Template.checkForMissing(Template.java:344)
        at com.samskivert.mustache.Template.getCompoundValue(Template.java:274)
        at com.samskivert.mustache.Template.getValue(Template.java:244)
        at com.samskivert.mustache.Template.getValueOrDefault(Template.java:292)
        at com.samskivert.mustache.Mustache$VariableSegment.execute(Mustache.java:872)
        at com.samskivert.mustache.Template.executeSegs(Template.java:170)
        at com.samskivert.mustache.Template.execute(Template.java:137)
        at com.samskivert.mustache.Template.execute(Template.java:128)
        at org.killbill.billing.plugin.notification.templates.MustacheTemplateEngine.executeTemplateText(MustacheTemplateEngine.java:32)
        at org.killbill.billing.plugin.notification.generator.TemplateRenderer.getEmailContent(TemplateRenderer.java:136)
        .......
```
Does anyone having the same issue with me?

**Comment by pierre** [comment]
Could you reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead? See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md). Thanks!
